# This is a basic workflow to help you get started with Actions

name: npm-publish

# Controls when the workflow will run
on: [push, workflow_dispatch]

permissions:
    packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: spritely/actions.publish-npm@add-github-auth
        with:
          packageRegistry: https://npm.pkg.github.com/
          packageRegistryToken: ${{ secrets.GITHUB_TOKEN }}
          projectDirectory: ./
          version: 1.0.0
